url: "https://noararazzak.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Noara Razzak" # the name of your site, e.g. ACME Corp.
description: "This is where I write about my research."
