url: "https://www.noararazzak.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "https://noararazzak.github.io" # the subpath of your site, e.g. /blog
title: "Statistics Done Right" # the name of your site, e.g. ACME Corp.
description: "This is where I write about my research."
