menu:
- {name: 'publications', url: '/publications'}
- {name: 'working papers', url: '/workingpapers'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

courses:
- {name: 'Principles of Microeconomics', url: 'principles_of_micro'}
- {name: 'Introduction to Statistics', url: 'intro_to_statistics'}
- {name: 'Statistics for Business and Economics', url: 'statistics_for_business_and_economics'}
- {name: 'Mathematics for Business and Economics', url: 'math_for_business_and_economics'}

social:
- {icon: 'github', link: 'https://github.com/noararazzak'}
- {icon: 'twitter', link: 'https://twitter.com/noararazzak'}


contacts:
- {name: 'Noara Razzak', department: 'John E. Walker Department of Economics', institution: 'Clemson University', institution_address: '320 Wilbur O. and Ann Powers Hall', phone: '(864) 656-3481', email: 'nrazzak(@)clemson.edu', image: 'assets/img/contact.jpg'}
