menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

courses:
- {name: 'Principles of Microeconomics', url: 'vector-calculus'}
- {name: 'Introduction to Statistics', url: 'quantum-mechanics'}
- {name: 'Statistics for Business and Economics', url: 'stellar-structures'}
- {name: 'Mathematics for Business and Economics', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/noararazzak'}
- {icon: 'twitter', link: 'https://twitter.com/noararazzak'}


contacts:
- {name: 'Noara Razzak', department: 'Department of Economics', institution: 'Clemson University', institution_address: '320 Wilbur O. and Ann Powers Hall', phone: '(864) 656-3481', email: 'nrazzak@clemson.edu', image: 'assets/img/contact.jpg'}
